language: python
python:
  - "3.6"
before_install:
  - chmod +x tests/behave.sh
install: "pip install -r requirements.txt coverage coveralls"
script:
  - mv tests/run_server.py .
  - tests/behave.sh
after_success:
  - coverage combine
  - coveralls
